apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tasks
  namespace: kafka
  labels:
    strimzi.io/cluster: taskflow-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
