apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: "some-metadata" # This is a placeholder, actual metadata might not be needed for default k8s secret store
    value: ""
scopes:
  - backend
  - worker
